### ISSUE TITLE
function fnv32

### ISSUE THREAD

**Issue by seafooler** [orcaman/concurrent-map#48] opened 2017-01-04 13:51 UTC
Thanks for your project!

I have a question that why you rewrite a fnv32 function while there is already a hash/fnv package.

**Comment by orcaman** [comment] 2017-01-04 14:12
@seafooler thanks! Most likely we didn't realize this exists as a native package. @swilly22 ?

**Comment by orcaman** [comment] 2017-01-05 08:51
@seafooler anyways, it would be awesome if you change the code to use the native package. If you will send a pull request with this change plus some benchmarks in the tests that show that it doesn't slow us down, we would happily merge it.

**Comment by seafooler** [comment] 2017-01-23 08:15
@orcaman Sorry for a delayed reply to you. 
I have tried it to replace the fnv32 function with the native package. However, I found that the performance is slowed down by 20%.
By the way, could you please explain why is your fnv32 function quicker than the native one
Thanks!

**Comment by dgtony** [comment] 2017-03-30 09:46
I did some naive benchmarking, and custom fnv32 implementation indeed is faster than the native one. Results for three runs on 10M array of strings with variable lengths: 0 - 128 symbols:

```
go test -bench=. -benchmem fnv32_bench_test.go
testing: warning: no tests to run
BenchmarkFNV32Custom-4        	20000000	        95.6 ns/op	       0 B/op	       0 allocs/op
BenchmarkFNV32NativeAlloc-4   	10000000	       249 ns/op	      74 B/op	       2 allocs/op
BenchmarkFNV32NativeReuse-4   	10000000	       167 ns/op	      70 B/op	       1 allocs/op
PASS
ok  	command-line-arguments	35.843s

go test -bench=. -benchmem fnv32_bench_test.go
testing: warning: no tests to run
BenchmarkFNV32Custom-4        	20000000	        90.8 ns/op	       0 B/op	       0 allocs/op
BenchmarkFNV32NativeAlloc-4   	10000000	       214 ns/op	      74 B/op	       2 allocs/op
BenchmarkFNV32NativeReuse-4   	10000000	       170 ns/op	      70 B/op	       1 allocs/op
PASS
ok  	command-line-arguments	40.216s

go test -bench=. -benchmem fnv32_bench_test.go
testing: warning: no tests to run
BenchmarkFNV32Custom-4        	20000000	        92.1 ns/op	       0 B/op	       0 allocs/op
BenchmarkFNV32NativeAlloc-4   	10000000	       215 ns/op	      74 B/op	       2 allocs/op
BenchmarkFNV32NativeReuse-4   	10000000	       165 ns/op	      70 B/op	       1 allocs/op
PASS
ok  	command-line-arguments	35.237s
```

It may be caused by memory allocations and interface dereferencing overhead in case of native implementation. Here is the benchmark code:
```
import (
	"hash/fnv"
	"math/rand"
	"testing"
)

const (
	MAX_ELEMS   = 10000000
	MAX_STR_LEN = 128
	letters     = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
)

// generate random string of given length
func randString(n int) string {
	b := make([]byte, n)
	for i := range b {
		b[i] = letters[rand.Int63()%int64(len(letters))]
	}
	return string(b)
}

// generate slice with MAX_ELEMS strings of variable length: 0 - MAX_STR_LEN
func prepareData() *[]string {
	var strLen int
	stringArray := make([]string, MAX_ELEMS)
	for i := 0; i < MAX_ELEMS; i++ {
		strLen = rand.Intn(MAX_STR_LEN)
		stringArray[i] = randString(strLen)
	}
	return &stringArray
}

// custom FNV32 from concurrent-map package
func fnv32(key string) uint32 {
	hash := uint32(2166136261)
	const prime32 = uint32(16777619)
	for i := 0; i < len(key); i++ {
		hash *= prime32
		hash ^= uint32(key[i])
	}
	return hash
}

var dataSet = prepareData()

func BenchmarkFNV32Custom(b *testing.B) {
	for i := 0; i < b.N; i++ {
		fnv32((*dataSet)[i%MAX_ELEMS])
	}
}

func BenchmarkFNV32NativeAlloc(b *testing.B) {
	for i := 0; i < b.N; i++ {
		hasher := fnv.New32()
		hasher.Write([]byte((*dataSet)[i%MAX_ELEMS]))
		hasher.Sum32()
	}
}

func BenchmarkFNV32NativeReuse(b *testing.B) {
	hasher := fnv.New32()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		hasher.Reset()
		hasher.Write([]byte((*dataSet)[i%MAX_ELEMS]))
		hasher.Sum32()
	}
}

```

**Comment by orcaman** [comment] 2017-03-30 10:30
Thanks @dgtony. I will try to contribute our implementation to the go project for the greater good. :-)

**Comment by orcaman** [comment] 2017-04-01 18:30
@seafooler @dgtony looks like the implementation in concurrent-map isn't really faster. Please refer to the proposal [here](https://github.com/golang/go/issues/19780) for more details. 

I'm going to go ahead and close this, thanks for sparkling this interesting discussion.

**Closed by orcaman** 2017-04-01 18:30 UTC
Labels: question
